# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "biscuit"
client_id = "f99a7e1b7b0e559392951409a9f070ea"
application_url = "https://re-dubai-tattoo-cams.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://re-dubai-tattoo-cams.trycloudflare.com/auth/shopify/callback",
  "https://re-dubai-tattoo-cams.trycloudflare.com/authSa/shopify/callback",
  "https://re-dubai-tattoo-cams.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "toanyasuo.myshopify.com"
